# Generated by Django 5.0.4 on 2024-04-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandlestickPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candlestick_pattern_name', models.CharField(max_length=150)),
                ('candlestick_image', models.ImageField(upload_to='')),
                ('candlestick_pattern_text', models.TextField(max_length=500)),
            ],
        ),
    ]
