# Generated by Django 5.0.4 on 2024-04-23 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
